version: '3.8'

services:
  wordpress:
    restart: always
    container_name: ${PROJECT_NAME}-wordpress
    build:
      dockerfile: Dockerfile # this line is actually redundant here - you need it only if you want to use some custom name for your Dockerfile
      context: ./ # a path to a directory containing a Dockerfile, or a URL to a git repository.

    ports:
      - ${LOCAL_SERVER_PORT}:80

    depends_on:
      - db

    env_file: .env

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: true
      PHP_IDE_CONFIG: serverName=${XDEBUG_SERVER_NAME}
      XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST} log=/tmp/xdebug.log
      XDEBUG_MODE: develop,debug

    volumes:
      - ./src/${WORDPRESS_CATALOG_NAME}:/var/www/html
      - ./src/${THEME_NAME}:/var/www/html/wp-content/themes/${THEME_NAME}
      - ./src/mu-plugins:/var/www/html/wp-content/mu-plugins

    networks:
      - backend-dev

  db:
    image: mariadb:10.4
    restart: always
    container_name: ${PROJECT_NAME}-mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend-dev

  phpmyadmin:
    image: phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - backend-dev

networks:
  backend-dev:

volumes:
  mariadb-data:
    driver: local